worker_processes 1;

events {
  worker_connections 1024;
}

http {
  lua_shared_dict ip_store 10m;

  server {
    listen 8080;

    location / {
      access_by_lua_file /usr/local/openresty/nginx/lua/rate_limit.lua;
      content_by_lua_block {
        local ip = ngx.var.remote_addr
        local dict = ngx.shared.ip_store
        local count = dict:get(ip)

        ngx.say("IP: ", ip)
        ngx.say("Current Count: ", count or 0)
      }
      log_by_lua_block {
        local ip = ngx.var.remote_addr
        local status = ngx.status
        local uri = ngx.var.request_uri

        ngx.log(ngx.ERR, "IP: ", ip, " URI: ", uri, " Status: ", status)
      }
    }
  }
}
