worker_processes 1;

events {
  worker_connections 1024;
}

http {
  lua_shared_dict ip_store 10m;

  resolver 127.0.0.11 valid=5s;

  server {
    listen 8080;

    location / {
      access_by_lua_file /usr/local/openresty/nginx/lua/token_bucket.lua;
      content_by_lua_block {
        local ip = ngx.var.remote_addr
        ngx.say("<Request Allowed>")
        ngx.say("IP: ", ip)
      }
      log_by_lua_block {
        local ip = ngx.var.remote_addr
        local status = ngx.status
        local uri = ngx.var.request_uri

        ngx.log(ngx.INFO, "IP: ", ip, " URI: ", uri, " Status: ", status)
      }
    }
  }
}
